In [79]:
import numpy as np

In [153]:
number_of_features = 3
number_of_outputs = 2

hidden_layers = [] # number of nodes in each layer
hidden_layers.append(2)

weight_matrices = []
biases = []

for i in range(len(hidden_layers)):
    matrix = None
    bias = np.zeros((hidden_layers[i], 1), dtype=np.float64)
    if i == 0:
        matrix = np.zeros((number_of_features, hidden_layers[i]), dtype=np.float64)
    else:
        matrix = np.zeros((hidden_layers[i-1], hidden_layers[i]), dtype=np.float64)
    
    weight_matrices.append(matrix)
    biases.append(bias)
    
matrix = np.zeros((hidden_layers[-1], number_of_outputs), dtype=np.float64)
bias = np.zeros((number_of_outputs, 1), dtype=np.float64)

weight_matrices.append(matrix)
biases.append(bias)

In [154]:
weight_matrices[0][0][0] = 0.1
weight_matrices[0][0][1] = 0.2
weight_matrices[0][1][0] = 0.3
weight_matrices[0][1][1] = 0.4
weight_matrices[0][2][0] = 0.5
weight_matrices[0][2][1] = 0.6

biases[0][0][0] = 0.5
biases[0][1][0] = 0.5

print(weight_matrices[0])
print(biases[0])

[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]]
[[0.5]
 [0.5]]


In [155]:
weight_matrices[1][0][0] = 0.7
weight_matrices[1][0][1] = 0.8
weight_matrices[1][1][0] = 0.9
weight_matrices[1][1][1] = 0.1

biases[1][0][0] = 0.5
biases[1][1][0] = 0.5

print(weight_matrices[1])
print(biases[1])

[[0.7 0.8]
 [0.9 0.1]]
[[0.5]
 [0.5]]


In [156]:
def activationFunction(z):
    return 1 / (1 + np.exp(-1 * z))
    # try:
    #     l = len(z)
    #     result = np.zeros((l, 1))
    #     for i in range(l):
    #         result[i][0] = 1 / (1 + np.exp(-z[i][0]))
        
    #     return result
    # except:
    #     return 1 / (1 + np.exp(-z))

In [157]:
def forwardPass(x):
    y_out = x

    for i in range(0,len(hidden_layers)+1):
        y_out = np.add(np.matmul(np.transpose(weight_matrices[i]), y_out), biases[i])
        y_out = activationFunction(y_out)
    return y_out

In [159]:
x_input = np.array([[1.0],[4.0],[5.0]], dtype=np.float16)
y_out = forwardPass(x_input)
print(y_out)

[[0.88955061]
 [0.80039961]]
