In [79]:
import numpy as np

In [115]:
number_of_features = 2
number_of_outputs = 1

hidden_layers = [] # number of nodes in each layer
hidden_layers.append(2)

weight_matrices = []
biases = []

for i in range(len(hidden_layers)):
    matrix = None
    bias = np.zeros((hidden_layers[i], 1), dtype=np.float64)
    if i == 0:
        matrix = np.zeros((number_of_features, hidden_layers[i]), dtype=np.float64)
    else:
        matrix = np.zeros((hidden_layers[i-1], hidden_layers[i]), dtype=np.float64)
    
    weight_matrices.append(matrix)
    biases.append(bias)
    
matrix = np.zeros((hidden_layers[-1], number_of_outputs), dtype=np.float64)
bias = np.zeros((number_of_outputs, 1), dtype=np.float64)

weight_matrices.append(matrix)
biases.append(bias)

In [138]:
weight_matrices[0][0][0] = 0.1
weight_matrices[0][0][1] = 0.4
weight_matrices[0][1][0] = 0.8
weight_matrices[0][1][1] = 0.6

biases[0][0][0] = 0
biases[0][1][0] = 0

print(weight_matrices[0])
print(biases[0])

[[0.1 0.4]
 [0.8 0.6]]
[[0.]
 [0.]]


In [139]:
weight_matrices[1][0][0] = 0.3
weight_matrices[1][1][0] = 0.9

biases[1][0][0] = 0.0

print(weight_matrices[1])
print(biases[1])

[[0.3]
 [0.9]]
[[0.]]


In [140]:
def activationFunction(z):
    return 1 / (1 + np.exp(-1 * z))
    # try:
    #     l = len(z)
    #     result = np.zeros((l, 1))
    #     for i in range(l):
    #         result[i][0] = 1 / (1 + np.exp(-z[i][0]))
        
    #     return result
    # except:
    #     return 1 / (1 + np.exp(-z))

In [150]:
def forwardPass(x):
    y_out = x

    for i in range(0,len(hidden_layers)+1):
        y_out = np.add(np.matmul(np.transpose(weight_matrices[i]), y_out), biases[i])
        y_out = activationFunction(y_out)
    return y_out

In [151]:
x_input = np.array([[0.35],[0.9]], dtype=np.float16)
y_out = forwardPass(x_input)
print(y_out)

[[0.6902817]]
