### <center> **Learn NUMPY** </center>

In [1]:
import numpy as np

In [5]:
arr1 = np.ones((3, 4))
arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
arr2 = np.zeros((4, 3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
arr = np.zeros_like(arr1)
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
arr = np.ones_like(arr2)
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
arr3 = np.full((3, 3), 100)
arr3

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [14]:
np.full_like(arr1, 55)

array([[55., 55., 55., 55.],
       [55., 55., 55., 55.],
       [55., 55., 55., 55.]])

In [18]:
arr = np.array([[1, 2, 3]])
arr4 = np.repeat(arr, 3, axis=0)
arr4

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [22]:
arr = np.arange(1, 10)
arr = np.reshape(arr, (3, 3))
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr = np.expand_dims(arr, axis=0)

In [29]:
arr5 = np.repeat(arr, 4, axis=0)
arr5

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [42]:
arr6 = np.array([3, 5, 9])
arr6 = np.expand_dims(arr6, axis=1)
arr6

array([[3],
       [5],
       [9]])

In [43]:
arr6 = np.repeat(np.expand_dims(arr6, axis=0), 4, axis=0)
arr6.shape

(4, 3, 1)

In [47]:
print(arr5.shape)
print(arr6.shape)

(4, 3, 3)
(4, 3, 1)


In [51]:
print(arr5)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [52]:
print(arr6)

[[[3]
  [5]
  [9]]

 [[3]
  [5]
  [9]]

 [[3]
  [5]
  [9]]

 [[3]
  [5]
  [9]]]


In [53]:
res = np.matmul(arr5, arr6)

In [55]:
print(res.shape)
print(res)

(4, 3, 1)
[[[ 40]
  [ 91]
  [142]]

 [[ 40]
  [ 91]
  [142]]

 [[ 40]
  [ 91]
  [142]]

 [[ 40]
  [ 91]
  [142]]]


In [58]:
arr5

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

<h4> <b>Transpose Of Matrix with 3-D</b> </h4>

In [65]:
np.transpose(arr6, axes=(0, 2, 1))

array([[[3, 5, 9]],

       [[3, 5, 9]],

       [[3, 5, 9]],

       [[3, 5, 9]]])

In [68]:
arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [67]:
arr1 + np.array([[3],[6],[10]])

array([[ 4.,  4.,  4.,  4.],
       [ 7.,  7.,  7.,  7.],
       [11., 11., 11., 11.]])

In [87]:
import time

total_length = 50
percentage = 0.0

while(True):
    percentage += 0.01
    percentage = np.minimum(percentage, 1.0)
    current_length = int(total_length * percentage)
    log_str = "=" * current_length + ">" + "." * (total_length - current_length)
    print(f"{log_str}", end="\r")
    if percentage >= 1.0:
        log_str = "=" * (total_length + 1)
        print(f"{log_str}", end="\r")
        break
    time.sleep(0.1)