In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing, model_selection

In [2]:
df = pd.read_csv('./Datasets/iris.csv')

In [3]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [5]:
df['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [6]:
label_encoder = preprocessing.LabelEncoder()
df['Species Encoded'] = label_encoder.fit_transform(df['Species'])

In [7]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species  \
0   1            5.1           3.5            1.4           0.2  Iris-setosa   
1   2            4.9           3.0            1.4           0.2  Iris-setosa   
2   3            4.7           3.2            1.3           0.2  Iris-setosa   
3   4            4.6           3.1            1.5           0.2  Iris-setosa   
4   5            5.0           3.6            1.4           0.2  Iris-setosa   

   Species Encoded  
0                0  
1                0  
2                0  
3                0  
4                0

In [8]:
label_encoder.inverse_transform([0, 1, 2, 2])

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica'], dtype=object)

In [9]:
data = np.array(df)

In [10]:
data[0:5]

array([[1, 5.1, 3.5, 1.4, 0.2, 'Iris-setosa', 0],
       [2, 4.9, 3.0, 1.4, 0.2, 'Iris-setosa', 0],
       [3, 4.7, 3.2, 1.3, 0.2, 'Iris-setosa', 0],
       [4, 4.6, 3.1, 1.5, 0.2, 'Iris-setosa', 0],
       [5, 5.0, 3.6, 1.4, 0.2, 'Iris-setosa', 0]], dtype=object)

In [11]:
train, test = model_selection.train_test_split(data, train_size=0.8)

In [12]:
train_x = train[:,1:-2]
train_y = np.expand_dims(train[:,-1], 1)

test_x = test[:,1:-2]
test_y = np.expand_dims(test[:,-1], 1)

In [13]:
print(train_x.shape)
print(train_y.shape)
print(train_x[0:2])
print(train_y[0:2])

(120, 4)
(120, 1)
[[5.6 2.9 3.6 1.3]
 [6.3 2.8 5.1 1.5]]
[[1]
 [2]]


# <center> **Neural Network** </center>

In [93]:
%run ./neural_network.ipynb

In [94]:
number_of_features = train_x.shape[1]
number_of_outputs = len(df['Species'].unique())
print(f"features : {number_of_features} \t outputs : {number_of_outputs}")

features : 4 	 outputs : 3


In [81]:
nn = NeuralNetwork(number_of_features, number_of_outputs, loss_function= CrossEntropyLoss(), output_activation_function=SoftmaxActivation())

In [82]:
nn.addHiddenLayer(Layer(2, activation_function=ReLUActivation()))

In [83]:
nn.initialize()

In [84]:
np.expand_dims(train_x[0], 1)

array([[5.6],
       [2.9],
       [3.6],
       [1.3]], dtype=object)

In [90]:
epochs = 100

nn.evaluate(train_x, train_y, learning_rate=0.05, epochs=epochs)

Epoch 0, oveservation 119 : loss = 4.6382038402254295
Epoch 1, oveservation 119 : loss = 4.6380361714935655
Epoch 2, oveservation 119 : loss = 4.6378704759751655
Epoch 3, oveservation 119 : loss = 4.63770675748939856
Epoch 4, oveservation 119 : loss = 4.6375450198437295
Epoch 5, oveservation 119 : loss = 4.6373852668329825
Epoch 6, oveservation 119 : loss = 4.6372275022393715
Epoch 7, oveservation 119 : loss = 4.6370717298316625
Epoch 8, oveservation 119 : loss = 4.6369179533658755
Epoch 9, oveservation 119 : loss = 4.6367661765831215
Epoch 10, oveservation 119 : loss = 4.6366164032115665
Epoch 11, oveservation 119 : loss = 4.6364686369639765
Epoch 12, oveservation 119 : loss = 4.6363228815388395
Epoch 13, oveservation 119 : loss = 4.6361791406185185
Epoch 14, oveservation 119 : loss = 4.6360374178707965
Epoch 15, oveservation 119 : loss = 4.6358977169463575
Epoch 16, oveservation 119 : loss = 4.6357600414804345
Epoch 17, oveservation 119 : loss = 4.6356243950903295
Epoch 18, oveservat

In [86]:
def getIndex(prob):
    res = 0
    mx = prob[0][0]
    for i in range(1, prob.shape[0]):
        if prob[i][0] > mx:
            res = i
            mx = prob[i][0]
    
    return res

In [91]:
prob = nn.predict(test_x)

true_predicted = 0
for i in range(len(prob)):
    pred = getIndex(prob[i])
    actual = test_y[i][0]
    print(f"pred : {pred} \t actual : {actual}")
    if pred == actual:
        true_predicted += 1

print(f"Correct predict : {true_predicted} out of {len(test_x)}")

pred : 0 	 actual : 0
pred : 1 	 actual : 1
pred : 0 	 actual : 0
pred : 0 	 actual : 0
pred : 0 	 actual : 0
pred : 0 	 actual : 0
pred : 0 	 actual : 0
pred : 0 	 actual : 0
pred : 1 	 actual : 1
pred : 1 	 actual : 1
pred : 1 	 actual : 1
pred : 0 	 actual : 0
pred : 0 	 actual : 0
pred : 2 	 actual : 2
pred : 0 	 actual : 0
pred : 2 	 actual : 2
pred : 0 	 actual : 0
pred : 0 	 actual : 0
pred : 2 	 actual : 2
pred : 1 	 actual : 1
pred : 2 	 actual : 2
pred : 1 	 actual : 1
pred : 0 	 actual : 0
pred : 0 	 actual : 0
pred : 1 	 actual : 1
pred : 1 	 actual : 1
pred : 0 	 actual : 0
pred : 2 	 actual : 2
pred : 0 	 actual : 0
pred : 2 	 actual : 2
Correct predict : 30 out of 30


In [89]:
print(nn.weights)

[array([[-7.89684457,  0.21962719],
       [-8.4492774 , -0.95938153],
       [13.13374724,  0.65350606],
       [15.73649244, -0.25083527]]), array([[-2.01083389,  0.71413034,  2.16110126],
       [-7.09567982,  3.62234387,  3.62663394]])]


In [92]:
print(nn.weights)

[array([[-7.86675508,  0.24804687],
       [-8.88894748, -1.05625505],
       [13.35979119,  0.68330262],
       [16.31501488, -0.32163252]]), array([[-2.01083399,  0.71848213,  2.15674956],
       [-7.31086741,  3.73262678,  3.73153862]])]
