In [66]:
import numpy as np
import pandas as pd
from sklearn import preprocessing, model_selection

In [67]:
df = pd.read_csv('../Datasets/iris.csv')

In [68]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [69]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [70]:
df['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [71]:
label_encoder = preprocessing.LabelEncoder()
df['Species Encoded'] = label_encoder.fit_transform(df['Species'])

In [72]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species  \
0   1            5.1           3.5            1.4           0.2  Iris-setosa   
1   2            4.9           3.0            1.4           0.2  Iris-setosa   
2   3            4.7           3.2            1.3           0.2  Iris-setosa   
3   4            4.6           3.1            1.5           0.2  Iris-setosa   
4   5            5.0           3.6            1.4           0.2  Iris-setosa   

   Species Encoded  
0                0  
1                0  
2                0  
3                0  
4                0

In [73]:
label_encoder.inverse_transform([0, 1, 2, 2])

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica'], dtype=object)

In [74]:
data = np.array(df)

In [75]:
data[0:5]

array([[1, 5.1, 3.5, 1.4, 0.2, 'Iris-setosa', 0],
       [2, 4.9, 3.0, 1.4, 0.2, 'Iris-setosa', 0],
       [3, 4.7, 3.2, 1.3, 0.2, 'Iris-setosa', 0],
       [4, 4.6, 3.1, 1.5, 0.2, 'Iris-setosa', 0],
       [5, 5.0, 3.6, 1.4, 0.2, 'Iris-setosa', 0]], dtype=object)

In [76]:
train, test = model_selection.train_test_split(data, train_size=0.8)

In [77]:
train_x = train[:,1:-2]
train_y = np.expand_dims(train[:,-1], 1)

test_x = test[:,1:-2]
test_y = np.expand_dims(test[:,-1], 1)

In [78]:
print(train_x.shape)
print(train_y.shape)
print(train_x[0:2])
print(train_y[0:2])

(120, 4)
(120, 1)
[[6.2 2.2 4.5 1.5]
 [5.9 3.0 4.2 1.5]]
[[1]
 [1]]


In [138]:
number_of_features = train_x.shape[1]
number_of_outputs = len(df['Species'].unique())
print(f"features : {number_of_features} \t outputs : {number_of_outputs}")

features : 4 	 outputs : 3


# <center> **Neural Network** </center>

In [157]:
%run ./neural_network.ipynb

In [166]:
nn = NeuralNetwork(number_of_features, number_of_outputs, loss_function=MeanSqureLoss(), output_activation_function=SoftmaxActivation())

In [167]:
nn.addHiddenLayer(Layer(2, activation_function=SigmoidActivation()))

In [168]:
nn.initialize()

In [176]:
epochs = 50

nn.evaluate(train_x, train_y, learning_rate=0.005, epochs=epochs)

Epoch 1, oveservation 120 : loss = 0.01590331358283249334
Epoch 2, oveservation 120 : loss = 0.01590136898065404743
Epoch 3, oveservation 120 : loss = 0.01589942324450195383
Epoch 4, oveservation 120 : loss = 0.01589747637228682784
Epoch 5, oveservation 120 : loss = 0.01589552836197472745
Epoch 6, oveservation 120 : loss = 0.01589357921158657024
Epoch 7, oveservation 120 : loss = 0.01589162891919842487
Epoch 8, oveservation 120 : loss = 0.01588967748294007836
Epoch 9, oveservation 120 : loss = 0.01588772490099597876
Epoch 10, oveservation 120 : loss = 0.01588577117160381435
Epoch 11, oveservation 120 : loss = 0.01588381629305476645
Epoch 12, oveservation 120 : loss = 0.01588186026369296477
Epoch 13, oveservation 120 : loss = 0.01587990308191500736
Epoch 14, oveservation 120 : loss = 0.01587794474617040586
Epoch 15, oveservation 120 : loss = 0.01587598525496003837
Epoch 16, oveservation 120 : loss = 0.01587402460683683847
Epoch 17, oveservation 120 : loss = 0.01587206280040523373
Epoch 

In [178]:
def getIndex(prob):
    res = 0
    mx = prob[0][0]
    for i in range(1, prob.shape[0]):
        if prob[i][0] > mx:
            res = i
            mx = prob[i][0]
    
    return res

In [179]:
prob = nn.predict(test_x)

true_predicted = 0
for i in range(len(prob)):
    pred = getIndex(prob[i])
    actual = test_y[i][0]
    print(f"pred : {pred} \t actual : {actual}")
    if pred == actual:
        true_predicted += 1

print(f"Correct predict : {true_predicted} out of {len(test_x)}")

pred : 0 	 actual : 0
pred : 0 	 actual : 0
pred : 0 	 actual : 0
pred : 2 	 actual : 2
pred : 0 	 actual : 0
pred : 0 	 actual : 0
pred : 2 	 actual : 2
pred : 0 	 actual : 0
pred : 2 	 actual : 2
pred : 2 	 actual : 2
pred : 1 	 actual : 1
pred : 2 	 actual : 2
pred : 1 	 actual : 1
pred : 1 	 actual : 1
pred : 0 	 actual : 0
pred : 2 	 actual : 1
pred : 0 	 actual : 0
pred : 0 	 actual : 0
pred : 0 	 actual : 0
pred : 1 	 actual : 1
pred : 2 	 actual : 2
pred : 2 	 actual : 2
pred : 2 	 actual : 2
pred : 2 	 actual : 2
pred : 0 	 actual : 0
pred : 2 	 actual : 2
pred : 2 	 actual : 2
pred : 0 	 actual : 0
pred : 2 	 actual : 2
pred : 0 	 actual : 0
Correct predict : 29 out of 30
