In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing, model_selection

In [2]:
df = pd.read_csv('../Datasets/iris.csv')

In [3]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [5]:
df['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [6]:
label_encoder = preprocessing.LabelEncoder()
df['Species Encoded'] = label_encoder.fit_transform(df['Species'])

In [7]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species  \
0   1            5.1           3.5            1.4           0.2  Iris-setosa   
1   2            4.9           3.0            1.4           0.2  Iris-setosa   
2   3            4.7           3.2            1.3           0.2  Iris-setosa   
3   4            4.6           3.1            1.5           0.2  Iris-setosa   
4   5            5.0           3.6            1.4           0.2  Iris-setosa   

   Species Encoded  
0                0  
1                0  
2                0  
3                0  
4                0

In [8]:
label_encoder.inverse_transform([0, 1, 2, 2])

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica'], dtype=object)

In [9]:
data = np.array(df)

In [10]:
data[0:5]

array([[1, 5.1, 3.5, 1.4, 0.2, 'Iris-setosa', 0],
       [2, 4.9, 3.0, 1.4, 0.2, 'Iris-setosa', 0],
       [3, 4.7, 3.2, 1.3, 0.2, 'Iris-setosa', 0],
       [4, 4.6, 3.1, 1.5, 0.2, 'Iris-setosa', 0],
       [5, 5.0, 3.6, 1.4, 0.2, 'Iris-setosa', 0]], dtype=object)

In [11]:
train, test = model_selection.train_test_split(data, train_size=0.8)

In [12]:
train_x = train[:,1:-2]
train_y = np.expand_dims(train[:,-1], 1)

test_x = test[:,1:-2]
test_y = np.expand_dims(test[:,-1], 1)

In [13]:
print(train_x.shape)
print(train_y.shape)
print(train_x[0:2])
print(train_y[0:2])

(120, 4)
(120, 1)
[[5.0 3.5 1.6 0.6]
 [5.4 3.9 1.3 0.4]]
[[0]
 [0]]


In [14]:
number_of_features = train_x.shape[1]
number_of_outputs = len(df['Species'].unique())
print(f"features : {number_of_features} \t outputs : {number_of_outputs}")

features : 4 	 outputs : 3


# <center> **Neural Network** </center>

In [19]:
%run ./neural_network_old.ipynb

In [20]:
nn = NeuralNetwork(number_of_features, number_of_outputs, loss_function=MeanSqureLoss(), output_activation_function=SoftmaxActivation())

In [21]:
nn.addHiddenLayer(Layer(2, activation_function=SigmoidActivation()))

In [22]:
nn.initialize()

In [41]:
epochs = 100

nn.fit(train_x, train_y, learning_rate=0.01, epochs=epochs)

Epoch 1, oveservation 120 : loss = 0.076974603745411186
Epoch 2, oveservation 120 : loss = 0.076870611100509058
Epoch 3, oveservation 120 : loss = 0.076767041221260976
Epoch 4, oveservation 120 : loss = 0.076663892949384055
Epoch 5, oveservation 120 : loss = 0.076561165110867126
Epoch 6, oveservation 120 : loss = 0.076458856516191364
Epoch 7, oveservation 120 : loss = 0.076356965960554154
Epoch 8, oveservation 120 : loss = 0.076255492224096475
Epoch 9, oveservation 120 : loss = 0.076154434072132036
Epoch 10, oveservation 120 : loss = 0.076053790255379313
Epoch 11, oveservation 120 : loss = 0.075953559510197355
Epoch 12, oveservation 120 : loss = 0.075853740558822524
Epoch 13, oveservation 120 : loss = 0.075754332109608543
Epoch 14, oveservation 120 : loss = 0.075655332857268325
Epoch 15, oveservation 120 : loss = 0.075556741483119046
Epoch 16, oveservation 120 : loss = 0.075458556655327837
Epoch 17, oveservation 120 : loss = 0.075360777029160286
Epoch 18, oveservation 120 : loss = 0.07

In [42]:
prob = nn.predict(test_x)

true_predicted = 0
for i in range(len(prob)):
    pred = np.argmax(prob[i])
    actual = test_y[i][0]
    print(f"pred : {pred} \t actual : {actual}")
    if pred == actual:
        true_predicted += 1

print(f"Correct predict : {true_predicted} out of {len(test_x)}")

pred : 1 	 actual : 1
pred : 0 	 actual : 0
pred : 0 	 actual : 0
pred : 2 	 actual : 2
pred : 2 	 actual : 2
pred : 1 	 actual : 1
pred : 1 	 actual : 1
pred : 1 	 actual : 1
pred : 0 	 actual : 0
pred : 2 	 actual : 2
pred : 2 	 actual : 2
pred : 0 	 actual : 0
pred : 2 	 actual : 2
pred : 2 	 actual : 2
pred : 0 	 actual : 0
pred : 2 	 actual : 2
pred : 1 	 actual : 1
pred : 2 	 actual : 2
pred : 0 	 actual : 0
pred : 0 	 actual : 0
pred : 0 	 actual : 0
pred : 1 	 actual : 1
pred : 1 	 actual : 1
pred : 2 	 actual : 2
pred : 1 	 actual : 1
pred : 1 	 actual : 1
pred : 2 	 actual : 2
pred : 2 	 actual : 2
pred : 1 	 actual : 1
pred : 2 	 actual : 2
Correct predict : 30 out of 30
